server:
  port: 10020
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: alone_dev
    password: nuo_alone
    url: jdbc:mysql://codegraffiti.cn:3306/alone?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
    open-in-view: false
  jackson:
    time-zone: GMT+8